### ISSUE TITLE
Verbs or nouns for method names?

### ISSUE THREAD

**Issue by domenic** [tc39/proposal-set-methods#10]
The new (non-Array) methods are inconsistently chosen:

- addElements/removeElements/intersect/subtract: verbs
- union: ambiguous, but usually a noun
- symmetricDifference: noun

Perhaps the simplest thing to do is converge on verbs by fixing #7 in favor of using "subtract" in both cases. "union" remains awkward, but what can you do.

**Comment by Ginden** [comment]
Using verbs for `addAll`/`deleteAll` and nouns for set theory methods seems to be best solution (`symmetricSubtract` have only 2 interesting results in Google).

Though, I'm not native speaker of English, so I don't feel confident enough to make decisions here.

**Comment by Ginden** [comment]
We agreed with @gsathya to use `xor` and `except`.
