### ISSUE TITLE
`Set.prototype.toggle()`

### ISSUE THREAD

**Issue by yukulele** [tc39/proposal-set-methods#106]
`Set` sorely lacks a `toggle` method:
```javascript
Set.prototype.toggle = function (value, toggle = this.has(value)) {
  return toggle
    ? this.delete(value)
    : this.size < this.add(value).size
}
```

**Comment by bakkot** [comment]
The set of methods in this proposal is already decided. Such a thing could be included in a different proposal, in principle, but it won't be included in this one.
