### ISSUE TITLE
cartesian product ?

### ISSUE THREAD

**Issue by salisbury-espinosa** [tc39/proposal-set-methods#107]
https://en.wikipedia.org/wiki/Cartesian_product

**Comment by bakkot** [comment]
While it's a useful operation, this proposal is ~finished and will not be including new methods.

**Comment by michaelficarra** [comment]
@salisbury-espinosa Feel free to create your own proposal though! Instructions on how to contribute are at https://github.com/tc39/ecma262/blob/main/CONTRIBUTING.md.
