### ISSUE TITLE
Consider adding a hasIntersection predicate

### ISSUE THREAD

**Issue by gautelo** [tc39/proposal-set-methods#108]
I often want to check whether there is some intersection between sets, and it feels wasteful to create the intersecting set if all I need is a predicate. I can use the negation of `isDisjointFrom`, but a `hasIntersection` or similar positively worded predicate would feel better in my opinion.

Would you consider adding that to the proposed set of methods, or has the proposal progressed too far to make changes now?

Thanks for your work. I'm really looking forward to these. :)

**Comment by bakkot** [comment]
This proposal is finished and is shipping in browsers. New features [can be proposed](https://github.com/tc39/ecma262/blob/main/CONTRIBUTING.md), of course, but they won't be part of this proposal.

For this specific thing, though, I think negating `isDisjointFrom` is the way to go. We don't usually add predicates which are just the negation of existing predicates.
