### ISSUE TITLE
Strange naming convention for returns-new-set

### ISSUE THREAD

**Issue by domenic** [tc39/proposal-set-methods#12]
Several methods are functionally identical to others, but use totally different names:

- union: addElements, but returns a new set instead of mutating the this value
- subtract: removeElements, but returns a new set instead of mutating the this value

Although I understand the set-theoretic origins of these terms, from a language-design level, this is a very strange precedent to set. I would expect we'd name these using a pattern that extends to other collections as well, instead of these idiosyncractic math-set names.

For example, as a strawperson, `withAddedElements()` / `withRemovedElements()` would be a more generalized pattern (cf. https://github.com/tc39/proposal-temporal/#with-function--all-civil-objects).

Alternately, we could remove these entirely, in favor of something like `.clone()` (or even `.slice()`) which would allow people to use any of the mutating methods in a returns-a-new-set way by chaining them, i.e. `s1.clone().addElements(x, y, z)` instead of `s1.withAddedElements(x, y, z)`.

In general I am uneasy with this new pattern being introduced for Set but not for the language's other collections.

**Comment by ljharb** [comment]
why not concat?

**Comment by Ginden** [comment]
`concat` would require consistency with expanding arrays and `Symbol.isConcatSpreadable`.

**Comment by ljharb** [comment]
Hm, I'm not sure that's true (re isConcatSpreadable); as far as expanding arrays; this would expand iterables (including Sets).

**Comment by Ginden** [comment]
That would be even more surprising - that `Array.prototype.concat` and `Set.prototype.concat` have different semantics.

**Comment by ljharb** [comment]
It's the same semantics, conceptually - "X.concat" takes an X-like and returns a new X that joins the two.

**Comment by domenic** [comment]
I'm torn on reusing concat. Definitely for the 99% case that most developers use it, the semantics are identical, and reusing the name would be really nice. But for the 1% case where isConcatSpreadable gets involved or multiple non-array-arguments are provided, that's a mismatch.

I wonder how bad it would be to have both, union() with simple semantics and concat() with complicated isConcatSpreadable/overloading on number of args semantics.

**Comment by ljharb** [comment]
Put another way, if the name `concat` gets used outside of arrays, the “isConcatSpreadable” and multi-arg edge cases would diminish drastically, and be seen even more as outliers instead of as part of inherent concatenation semantics.

**Comment by gsathya** [comment]
This proposal no longer includes addElements or removeElements, so there's no duplication. Closing.
