### ISSUE TITLE
What about .intersects or .disjoint?

### ISSUE THREAD

**Issue by gsathya** [tc39/proposal-set-methods#16]
From https://twitter.com/maximekjaer/status/954293396440526849:

"It could be nice to have .disjoint or .intersects, returning booleans. Those might be slightly more efficient than `a.intersection(b).size === 0`"

**Comment by gsathya** [comment]
I'm not too excited about this because it would be just slightly more optimized (one extra allocation) and the extra syntax isn't too much, but I don't feel too strongly about it.

**Comment by rbuckton** [comment]
I started looking into some of these as well: https://gist.github.com/rbuckton/5f1336933c23026e97cc1a8ed8be8f3a
