### ISSUE TITLE
Link to spec is broken 

### ISSUE THREAD

**Issue by gsathya** [tc39/proposal-set-methods#22]
both in the description of https://github.com/tc39/set-methods (at the top) and the readme

**Comment by michaelficarra** [comment]
https://tc39.github.io/set-methods/ works.

**Comment by ljharb** [comment]
Repo links redirect; but github pages links don't.

**Comment by mathiasbynens** [comment]
https://github.com/tc39/set-methods should probably be renamed to https://github.com/tc39/proposal-set-methods

**Comment by Ginden** [comment]
@gsathya I can't update repository description on GitHub anymore (I lost it after transfer). Probably some member of TC39 organisation have to do this.

I will update README, though.

PS. @mathiasbynens is right.

**Comment by Ginden** [comment]
Fixed link in README. Someone with admin access to repository have to change link in description (@littledan?).

**Comment by littledan** [comment]
@Ginden Are you still missing admin access? For me, in Settings, it looks like you do have that access.

**Comment by Ginden** [comment]
@littledan Not sure why I didn't have, now everything is fine.
