### ISSUE TITLE
Set should be compatible with complex objects

### ISSUE THREAD

**Issue by phillijw** [tc39/proposal-set-methods#25]
Solve this problem: https://stackoverflow.com/questions/29759480/how-to-customize-object-equality-for-javascript-set

**Comment by bakkot** [comment]
That's something worth investigating (and we've been talking about it on and off for years), but I think it's probably out of scope for this proposal.

**Comment by c69** [comment]
Its completely unrelated to Set methods.
Discussion about custom `.equals` or operator overloading or value types, historically never got anywhere ...
P.s.: checked Stackoverflow accepted answer - yes, its all explained there.

**Comment by Ginden** [comment]
Out of scope, closed.
