### ISSUE TITLE
Spec reviewer signoff

### ISSUE THREAD

**Issue by gsathya** [tc39/proposal-set-methods#32]
Part of the stage 2 → 3 requirements is signoff from the official spec reviewers. Please review!

- [ ] @michaelficarra 
- [x] @bakkot 
- [x] @rwaldron 
- [ ] @tabatkins

**Comment by ljharb** [comment]
It seems that all of the new methods lack the `If S does not have a [[SetData]] internal slot, throw a TypeError exception.` check that `Set.prototype.add` has. Why do they lack it?

**Comment by ljharb** [comment]
Could intersection/union perhaps make use of https://tc39.github.io/ecma262/#sec-add-entries-from-iterable ?

**Comment by ljharb** [comment]
The `length` notes are only needed when the length doesn't match the implicit algorithm in https://tc39.github.io/ecma262/#sec-ecmascript-standard-built-in-objects - (btw, there's an `isDisjoinWith` misspelling in a number of places), so none of these need an explicit `length` definition.

**Comment by gsathya** [comment]
Thanks for the quick review!

> It seems that some of the new methods lack the If S does not have a [[SetData]] internal slot, throw a TypeError exception. check that Set.prototype.add has. Could that be added?

I left those out because some of these call out to the underlying `Set.prototype.add`, `Set.prototype.has` & `Set.prototype.delete` methods which do the type check. This also makes these methods work seamlessly for those who monkey patch the `add`/`has`/`delete` method, like how the `SetConstructor` works. Do you think it's necessary to the type check here as well?

`isSubsetOf` and `isDisjointWith` directly use the [[SetData]] internal slot of the Set object, which requires the type check. I could remove the type check from `isSupersetOf`, if you think that's better?

> Could intersection/union perhaps make use of https://tc39.github.io/ecma262/#sec-add-entries-from-iterable ?

Interesting idea. I think it'd be better to create a similar `AddEntryFromIterable` that works for Sets, rather than Maps. Then we could refactor out code from the `SetConstructor` and share it with `union`/`intersection`, What do you think?

> The length notes are only needed when the length doesn't match the implicit algorithm in https://tc39.github.io/ecma262/#sec-ecmascript-standard-built-in-objects - (btw, there's an isDisjoinWith misspelling in a number of places), so none of these need an explicit length definition.

Fixed in https://github.com/tc39/proposal-set-methods/pull/33.

**Comment by ljharb** [comment]
(I just put up https://github.com/tc39/ecma262/pull/1373 ; if that lands, then it'll be slightly less boilerplate for you to have this check on all the Set methods :-D )

**Comment by bakkot** [comment]
I'll try to do this soon. Do you have a timescale for this? E.g. are you hoping to present at the January meeting?

**Comment by gsathya** [comment]
> I'll try to do this soon. Do you have a timescale for this? E.g. are you hoping to present at the January meeting?

Thanks! Yes, I'm hoping to present this in January and ask for Stage 3.

**Comment by rwaldron** [comment]
Just finished my review. Nitpick: I would use the same variable naming conventions as the existing spec, for example: _newSet_ => _S_ (or change the spec to the much nicer _newSet_). Everything else that stood out has already been mentioned here or in #35, so I will consider my review complete.

**Comment by gsathya** [comment]
@bakkot, @tabatkins, @michaelficarra -- I think the spec is in a really good shape now (with @bakkot's concerns being addressed). Please do review and let me know if there are any issues. I'd like to present this for Stage 3 at the January meeting.

**Comment by bakkot** [comment]
LGTM. I continue to disagree on #43, but I've made my case. If you can get consensus from the rest of the committee on the current eager behavior, the spec text for it seems fine.

I also want to note explicitly that this doesn't do the fall-back-to-iterator thing for the receiver of `isSupersetOf` and `isDisjointWith` discussed in https://github.com/tc39/proposal-set-methods/pull/41#issuecomment-453305763. I don't necessarily mind this; I agree that supporting calling these methods with a non-Set receiver is very much an edge case. (Also, I realized that `.call`ing `.union` on for example an Array will do entirely the wrong thing, because of SpeciesConstructor, so it seems less important to make `.call`ing other methods on non-`Set`s work.) Just wanted to make sure it was intentional and noted.

**Comment by gsathya** [comment]
>LGTM. I continue to disagree on #43, but I've made my case. If you can get consensus from the rest of the committee on the current eager behavior, the spec text for it seems fine.

Thanks. I definitely plan to bring this up to the committee during my presentation.

>  I also want to note explicitly that this doesn't do the fall-back-to-iterator thing for the receiver of isSupersetOf and isDisjointWith discussed in #41 (comment). I don't necessarily mind this; I agree that supporting calling these methods with a non-Set receiver is very much an edge case.

ACK

**Comment by michaelficarra** [comment]
@gsathya Can you summarise the design changes (and their implications) that resulted from all of the recent discussions? I'm unsure whether we've reached enough stability in the design to ask for stage 3 yet.

**Comment by gsathya** [comment]
> Can you summarise the design changes (and their implications) that resulted from all of the recent discussions?

Sure, I'll update this issue once I make this summary for my TC39 presentation.

>  I'm unsure whether we've reached enough stability in the design to ask for stage 3 yet.

Yeah, fair enough. I doubt we can come to consensus on https://github.com/tc39/proposal-set-methods/issues/50 by next week

**Comment by bakkot** [comment]
This got stage 3! Cleaning up old issues.
