### ISSUE TITLE
isSubsetOf: should it be generic as well?

### ISSUE THREAD

**Issue by ljharb** [tc39/proposal-set-methods#37]
Should `isSubsetOf` be able to work on any iterable receiver, instead of relying on [[SetData]]?

**Comment by ajklein** [comment]
Part of the answer to this question is what I was getting at in the last paragraph of my [comment](https://github.com/tc39/proposal-set-methods/issues/35#issuecomment-448423425) on #35. I think it's best to keep this discussion going over there. But the short version is, it's not as simple to make isSubsetOf work completely-generically.

**Comment by gsathya** [comment]
Fixed in https://github.com/tc39/proposal-set-methods/pull/45
