### ISSUE TITLE
Abstract op for SetSpeciesCreate?

### ISSUE THREAD

**Issue by ljharb** [tc39/proposal-set-methods#49]
After the latest round of changes, I wanted to start fresh and summarize my updated thought process:
<details>

### Produce a new set
These species-construct a new set from the receiver.
 - union
 - intersection
 - difference
 - symmetricDifference

### "Addable"
These create a contract around having an "add" method.
 - union
 - intersection
 - symmetricDifference

### "Queryable"
These create a contract around having a "has" method.
 - intersection
 - isSubsetOf
 - isSupersetOf
 - isDisjointFrom

### "Deletable"
These create a contract around having a "delete" method.
 - difference
 - symmetricDifference

### Generic receiver
These work with a non-Set iterable receiver:
 - isSubsetOf
 - isSupersetOf
 - isDisjointFrom
</details>

-----

Would it be cleaner to make an abstract operation for `SetSpeciesCreate(set)`, like `ArraySpeciesCreate`, to DRY up these spec steps a bit?

**Comment by bakkot** [comment]
Current plan is to not use `Symbol.species` at all, so closing this. If we do decide to use `Symbol.species` I'll re-open.
