### ISSUE TITLE
How about Set.prototype.pop() or Set.prototype.last?

### ISSUE THREAD

**Issue by doasync** [tc39/proposal-set-methods#55]

**Comment by ljharb** [comment]
What's the use case? Sets have insertion order, but beyond being deterministic, the ordering isn't usually relevant in code i've seen.

**Comment by doasync** [comment]
https://stackoverflow.com/questions/34583643/get-last-value-inserted-into-a-set

**Comment by ljharb** [comment]
If you're wrapping a Set, then you could wrap the `add` method to keep track of the last item added, no?

**Comment by doasync** [comment]
Yes, but why bother to wrap it. The only method we need to manage stacks with sets is `.pop()`

**Comment by doasync** [comment]
https://www.quora.com/What-are-the-real-life-applications-of-stack-data-structure

**Comment by ljharb** [comment]
Sets aren't a stack tho, they're a set. Arrays are stacklike as well; is there a reason a Set is needed when an Array already has that semantic?

**Comment by doasync** [comment]
`A value in the Set may only occur once; it is unique in the Set's collection.`

**Comment by zloirock** [comment]
Current proposal contains methods based on set theory, so it's rather an issue for https://github.com/tc39/proposal-collection-methods. Also, I agree with @ljharb argumentation.

**Comment by ljharb** [comment]
@doasync sure but that's not a property of stacks, it's a property of sets.

**Comment by doasync** [comment]
Yeah, ok, thanks

**Comment by doasync** [comment]
They already have an issue about `.pop`:
https://github.com/tc39/proposal-collection-methods/issues/1
