### ISSUE TITLE
Method to test equality ?

### ISSUE THREAD

**Issue by rik** [tc39/proposal-set-methods#69]
As far as I can tell, there is no proposal to test equality between two sets. How about `Set.prototype.equals(iterable)` ?

**Comment by ljharb** [comment]
`set.symmetricDifference(other).size === 0`?

**Comment by zloirock** [comment]
@ljharb sounds like with `array.filter(a => a === b).length !== 0` we don't need `.includes`.

**Comment by ljharb** [comment]
@zloirock i don't believe i was making that argument.

**Comment by Ginden** [comment]
We also don't have a method to test for array equality and this idea was never (?) raised. Seems like a very minor use case.

**Comment by bakkot** [comment]
I'm going to close this as out of scope for this proposal; we've settled on the methods to include. It's possible someone will pick this up later, though, possibly as part of a broader effort to add equality testing methods.

In the mean time, you can use `let setEquals = (a, b) => a.size === b.size && a.isSubsetOf(b)`.
