### ISSUE TITLE
Rename subtract to difference?

### ISSUE THREAD

**Issue by gsathya** [tc39/proposal-set-methods#7]
This would make it consistent with symmetricDifference. What do you think?

**Comment by Ginden** [comment]
@tabatkins noticed problem with naming of this method in #2. I personally prefer `subtract` because it's consistent with  Immutable.js API. Though, most programming languages or libraries (Lisp, Python, Guava) use `difference`. 

https://en.wikipedia.org/wiki/Complement_(set_theory)#Complements_in_various_programming_languages

**Comment by Ginden** [comment]
I think more feedback is required.

I personally prefer `.except` or `.subtract` because it's immediately obvious what such method do. `difference` doesn't have this advantage, even if it's more correct in regard to "difference" in set theory.

**Comment by domenic** [comment]
I would prefer that symmetricDifference and this method be aligned in naming, by renaming either one of them (no strong opinion on which).

**Comment by ljharb** [comment]
One issue with “difference” may be that it doesn’t suggest as strongly a direction as subtract does.

**Comment by Ginden** [comment]
> I would prefer that symmetricDifference and this method be aligned in naming, by renaming either one of them (no strong opinion on which).

Polyfill used name `.xor` for symmetric difference operation. Not sure if it's better.

**Comment by Ginden** [comment]
Done in df8e4c5

**Comment by Ginden** [comment]
Done in df8e4c5

**Comment by tabatkins** [comment]
Sorry for this being back-and-forth, but `difference` has the same lack of implicit ordering as `complement` did - it's not immediately, intuitively clear which element's values are retained.  `minus` and `subtract` are both good; `removeAll`, while it implies mutation semantics, is also *extremely* clear and good in this regard.

Related: "symmetricDifference" vastly exceeds my design instincts for what is an allowable level of spelling difficulty in an API.  "symmetric" is not an easy word to spell (my fingers just now tried to type it with a single "m"!), and combined with *another* 10 letters after, it's huge and terrible.  `xor` has a non-obvious meaning for many people, including native English speakers, but it's short and easy to spell; unsure if it's good enough or not.

**Comment by ljharb** [comment]
`withoutAll`?

**Comment by Ginden** [comment]
`except`?

**Comment by Ginden** [comment]
We decided with @gsathya to use name `except`.
