### ISSUE TITLE
My proposals to repository `proposal-set-methods`

### ISSUE THREAD

**Issue by brunolnetto** [tc39/proposal-set-methods#80]
Hi,

Is the microphone on? I mean, is this an official initiative? I have two (if not more) suggestions to incorporate:

1. Objects handling: https://github.com/quivero/prego/blob/main/utils/objects/objects.js
2. Euler diagrams: https://github.com/trouchet/eulejs

Feel free to ask, refute or refuse.

**Comment by bakkot** [comment]
Thanks for the suggestions, but we're content with the current collection of methods.
