### ISSUE TITLE
Method names as verbs

### ISSUE THREAD

**Issue by FrameMuse** [tc39/proposal-set-methods#93]
"union" can be either a verb or noun, and "intersect" (the verb) is shorter than "intersection"; this suggests that using verbs might be a win.

_Originally posted by @tabatkins in https://github.com/tc39/proposal-set-methods/issues/24#issuecomment-388479218_
            

I think that we should pick verbs for method names that _creates something_ since **we can** and this is want JS tends to choose.
For example:
- Array: slice, pop, shift, fill, filter, find, ...
- String: concat, sub, replace, repeat, search
We see that for an **Action** a verb is usually used, for getting, testing and converting values alternative syntax is being used like:
- length (a noun) - get a length
- toString (a directional `to`) - convert to string
- includes (`s` ending for a verb) - it includes?
- isPrototypeOf (a plain question sentence) - is this a prototype of ...?

By this, I suggest using names like
- unite, unionize for `union`
- intersect for `intersection`
- differ for `difference`
- differBoth for `symmetricDifference`
- other names follow the rule above, so they're unchanged.

**Comment by bakkot** [comment]
Thanks for the suggestion, but the names are already decided.
